app:
  domains:
    user:
      rules:
        name:
          maxNameLength: 32
          minNameLength: 6

drivers:
  mongo:
    connections:
      atlas_primary:
        uri: MONGODB_ATLAS_PRIMARY
        domains:
          user:
            - database: primary
              collections:
                user: user
                sessions: sessions

          cards:
            - database: secondary
              collections:
                cards: cards
