app:
  domains:
    user:
      rules:
        name:
          maxNameLength: 32
          minNameLength: 6

shared:
  eventManager:
    eventFailureLockPeriod: 1.8e+6 #30 minutes
    eventTimeoutPeriod: 120000 #2 minutes

drivers:
  mongo:
    connections:
      atlas_primary:
        uri: MONGODB_ATLAS_PRIMARY
        domains:
          user:
            - database: primary
              collections:
                user: user
                sessions: sessions

        shared:
          events:
            database: events #All of the collections need to belong to one database to allow aggregation.
            collections:
              eventFailure: event-failure
              eventHandler: event-handler
              event: event
